server:
  port: 5503
  host: localhost
auth:
  jwksUri: http://localhost:5000/.well-known/jwks.json
database:
  url: mongodb+srv://saudjavaid2003_db_user:Z1YoAQM5mUUXofVj@cluster0.mcmgqnl.mongodb.net/order?appName=Cluster0
frontend:
  clientUi: 'http://localhost:3000'
kafka:
  broker: 'localhost:9092'
stripe:
  secretKey: 'sk_test_51TV1z92z5lzN9eXqRtHkWsG4l2mZxddZCAq50fU2NLVYuR1oVeRxo1l8m4ChmgHitn1x86XF3abICkZpIoD10Ak800FdvSZSbN'